args:
  backbone: vitae
  mode: none
  img_size: 256
config:
  dec_depth: 8
  enc_depth: 1
  input_nc: 3
  output_nc: 3
  resnet_stages_num: 4
  token_len: 4
  with_pos: learned
net_name: BIT_Transformer
